### ISSUE TITLE
Universe is not created when watching all the namespaces

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-k8s-operator#9]
**Describe the bug**
I deployed the operator on OpenShift cluster having kubernetesOperatorNamespace with a blank value i.e. the default. After creating an universe CR, nothing happens. The status field remains blank and the operator logs have no entries for YBUniverseReconciler.

**To Reproduce**
- Install the operator without setting kubernetesOperatorNamespace.
- Create an universe CR.

**Expected behavior**
The universe creation should get started.

**Additional context**
Operator version: 0.1.3

**Comment by amannijhawan** [comment]
Verified that multiple namespace mode works.
